[tool.poetry]
name = "hubitat"
version = "0.6.8"
description = "A Hubitat integration for Home Assistant"
authors = ["Jason Cheatham <jason@jasoncheatham.com>"]
packages = [
	{ include = "custom_components" }
]

[tool.poetry.dependencies]
python = "^3.8.0"

[tool.poetry.dev-dependencies]
black = "^20.8b1"
flake8 = "^3.8.1"
isort = "^4.3.21"
pre-commit = "^2.4.0"
flake8-pyi = "^20.5.0"
hubitatmaker = "^0.5.2"
homeassistant = "2021.7.0b0"
pytest-homeassistant-custom-component = "^0.4.2"
neovim = "^0.3.1"
pytest-asyncio = "^0.15.1"

[tool.poetry.scripts]
init = "scripts:init"
test = "scripts:test"
copy = "scripts:copy"

[tool.pytest.ini_options]
testpaths = ["tests"]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
